logging:
  level: INFO

tasks:
  jm:
    enabled: ${JM_ENABLED:true}
    username: ${JM_USERNAME}
    password: ${JM_PASSWORD}

notification:
  enabled: true
  policy: ${NOTIFICATION_POLICY:always}
  channel:
    type: ${NOTIFICATION_TYPE:console}
    config: {}
